### ISSUE TITLE
Don't rename .ending.yyy

### ISSUE THREAD

**Issue by marcesengel** [HeroProtagonist/recursive-rename#7]
Hey @HeroProtagonist ,

what do you think about supporting conversations only for exact matches?

I expected it that way and was pretty surprised when my `index.js.map` was renamed to `index.mjs`. Otherwise great tool, loving the colored output :heart_eyes: 

I'd be happy to create a PR in case you agree. Probably could make this an option as well (if you think it shouldn't always behave they way I suggested).

Have a nice day!

**Comment by HeroProtagonist** [comment]
closing with merge of #15 version 4+ has this now
